<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'John Doe',
                'email' => 'johndoe@example.com',
                'password' => Hash::make('password123'),
                'phone_number' => '123456789',
                'image_profile' => 'profile1.jpg',
                'is_active' => true,
                'birthday' => '1990-01-01',
                'gender' => 'male',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jane Smith',
                'email' => 'jane@example.com',
                'password' => Hash::make('password123'),
                'phone_number' => '987654321',
                'image_profile' => 'profile2.jpg',
                'is_active' => true,
                'birthday' => '1992-05-15',
                'gender' => 'female',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nguyen Van A',
                'email' => 'nguyenvana@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0901111111',
                'image_profile' => 'profile3.jpg',
                'is_active' => true,
                'birthday' => '1995-03-10',
                'gender' => 'male',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tran Thi B',
                'email' => 'tranthib@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0902222222',
                'image_profile' => 'profile4.jpg',
                'is_active' => true,
                'birthday' => '1996-07-21',
                'gender' => 'female',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Le Van C',
                'email' => 'levanc@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0903333333',
                'image_profile' => 'profile5.jpg',
                'is_active' => true,
                'birthday' => '1993-11-05',
                'gender' => 'male',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pham Thi D',
                'email' => 'phamthid@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0904444444',
                'image_profile' => 'profile6.jpg',
                'is_active' => true,
                'birthday' => '1994-02-14',
                'gender' => 'female',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hoang Van E',
                'email' => 'hoangvane@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0905555555',
                'image_profile' => 'profile7.jpg',
                'is_active' => true,
                'birthday' => '1991-09-09',
                'gender' => 'male',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vu Thi F',
                'email' => 'vuthif@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0906666666',
                'image_profile' => 'profile8.jpg',
                'is_active' => true,
                'birthday' => '1997-12-12',
                'gender' => 'female',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Do Van G',
                'email' => 'dovang@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0907777777',
                'image_profile' => 'profile9.jpg',
                'is_active' => true,
                'birthday' => '1998-04-18',
                'gender' => 'male',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bui Thi H',
                'email' => 'buithih@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0908888888',
                'image_profile' => 'profile10.jpg',
                'is_active' => true,
                'birthday' => '1999-06-25',
                'gender' => 'female',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pham Van I',
                'email' => 'phamvani@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0909999999',
                'image_profile' => 'profile11.jpg',
                'is_active' => true,
                'birthday' => '1992-08-30',
                'gender' => 'male',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nguyen Thi K',
                'email' => 'nguyenthik@example.com',
                'password' => Hash::make('12345678'),
                'phone_number' => '0910000000',
                'image_profile' => 'profile12.jpg',
                'is_active' => true,
                'birthday' => '1993-10-11',
                'gender' => 'female',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('admin123'),
                'phone_number' => '0999999999',
                'image_profile' => 'admin.jpg',
                'is_active' => true,
                'birthday' => '1990-01-01',
                'gender' => 'male',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        
    }
}


